//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manual_ASP_NET_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Consulta
    {
        [Key]
        public int IdPaciente { get; set; }
        [Key]
        public int IdMedico { get; set; }
        [Key]
        public System.DateTime Fecha { get; set; }
        public string Sintomas { get; set; }
        public string Diagnostico { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
